#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
skill="$root/skills/apex-combat-review/SKILL.md"
readme="$root/README.md"

test -f "$skill"
test -f "$readme"

grep -q "name: apex-combat-review" "$skill"
grep -q "game-video-analysis-mcp" "$skill"
grep -q "apex-reference-mcp" "$skill"
grep -q "Observed information" "$skill"
grep -q "Options available" "$skill"
grep -q "Actual action" "$skill"
grep -q "Evaluation" "$skill"
grep -q "observed" "$skill"
grep -q "inferred" "$skill"
grep -q "unknown" "$skill"
grep -q "Do not call a play correct only because the player survived" "$skill"
grep -q "Do not call a play wrong only because the player died" "$skill"
grep -q "Push, Hold, or Reset Decisions" "$skill"
grep -q "Do not mark \"should have pushed\" from an enemy shield crack alone" "$skill"
grep -q "Evaluate the expected value at the moment of decision" "$skill"
grep -q "Push is reasonable" "$skill"
grep -q "Holding is reasonable" "$skill"
grep -q "Resetting is reasonable" "$skill"
grep -q "Heal, Reload, and Inventory Decisions" "$skill"
grep -q "Opening the inventory is not automatically a mistake" "$skill"
grep -q "Do not write \"bad because the inventory was opened.\"" "$skill"
grep -q "Safe inventory management" "$skill"
grep -q "Punishable inventory management" "$skill"
grep -q "Heal continuation" "$skill"
grep -q "Heal cancel" "$skill"
grep -q "Reload decision" "$skill"
grep -q "Do not over-prioritize self-recovery" "$skill"
grep -q "Line of Sight, Cover, and Positioning Decisions" "$skill"
grep -q "Do not stop at \"use cover.\"" "$skill"
grep -q "Enemy line count" "$skill"
grep -q "Cover quality" "$skill"
grep -q "Peek exposure" "$skill"
grep -q "Ally angles" "$skill"
grep -q "Team overlap" "$skill"
grep -q "Next cover" "$skill"
grep -q "Evaluate cover against the objective" "$skill"
grep -q "Favor cross formation" "$skill"
grep -q "Mark isolation" "$skill"
grep -q "Attack through next cover" "$skill"
grep -q "Hold a protected cross" "$skill"
grep -q "Retreat in stages" "$skill"
grep -q "Poor same-cover overlap" "$skill"
grep -q "Audio Information Decisions" "$skill"
grep -q "Audio is decision evidence" "$skill"
grep -q "Audio event type" "$skill"
grep -q "Estimated direction" "$skill"
grep -q "Estimated distance" "$skill"
grep -q "Confidence" "$skill"
grep -q "Source ambiguity" "$skill"
grep -q "Counterfactual baseline" "$skill"
grep -q "Treat footsteps as pressure evidence" "$skill"
grep -q "When audio and video conflict" "$skill"
grep -q "Footstep warning changes a hold" "$skill"
grep -q "Healing sound creates a push window" "$skill"
grep -q "Revive sound changes priority" "$skill"
grep -q "Reload sound supports a swing" "$skill"
grep -q "Zipline and gunfire suggest retreat risk" "$skill"
grep -q "Expected Review Shape" "$skill"
grep -q "apex-combat-review" "$readme"

echo "validation passed"
